In [8]:
import pandas as pd
import os

if not os.path.exists("baseline_df_names.csv"):
    df = pd.read_csv("baseline_df_full.csv")
    df[["name"]].to_csv("baseline_df_names.csv", index=False)

df.head(10)

                                      name
0       "Angel Kanchev" University of Ruse
1        "Horthy Miklós" Air Force Academy
2    "Prof. Dr. Assen Zlatarov" University
3                               1 December
4  1 Decembrie 1918 University, Alba Iulia
5  21 Sheptytskoho Square, Ivano-Frankivsk
6          2nd Military Medical University
7        2nd Omsk Military Infantry School
8          3rd Military Medical University
9                                    42 FR

In [10]:
df = pd.read_csv("baseline_df_names.csv")
print(f"Rows before cleaning: {len(df)}")

# Remove rows where name is empty string
df_cleaned = df[df["name"].notna()].reset_index(drop=True)
print(f"Rows after removing empty names: {len(df_cleaned)}")

df_cleaned.head(10)

Rows before cleaning: 16612
Rows after removing empty names: 15895

                                      name
0       "Angel Kanchev" University of Ruse
1        "Horthy Miklós" Air Force Academy
2    "Prof. Dr. Assen Zlatarov" University
3                               1 December
4  1 Decembrie 1918 University, Alba Iulia
5  21 Sheptytskoho Square, Ivano-Frankivsk
6          2nd Military Medical University
7        2nd Omsk Military Infantry School
8          3rd Military Medical University
9                                    42 FR

In [12]:
if not os.path.exists("baseline_df_names_cleaned.csv"):
    df_cleaned.to_csv("baseline_df_names_cleaned.csv", index=False, header=False)